title: <p align="center"> Aditya Regundwar </p>
logo: /assets/img/Photo Aditya Regundwar.jpg
description: Working as Data Sceintist for 2.5 years. Workd on different projects in various domain.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
